Repository Ureca-Dangdang-salon/dang_client, pull requests merged in 2024-12, with the labels that each got.

#68 fix: navbar redundant code
  src/components/Common/Navbar/Navbar.jsx
Labels: 🔨 Refactor

#69 소셜로그인 회원가입 연동
  src/api/apiClient.js
  src/api/auth.js
  src/api/requestUrls.js
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Layout/NotFound.jsx
  src/components/login/GLoginButton.jsx
  src/components/login/KLoginButton.jsx
  src/components/login/LoginButton.jsx
  src/components/login/NLoginButton.jsx
  src/pages/Login.jsx
  src/pages/Survey/Survey.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  vite.config.js
Labels: 📬 API

#66 survey page update
  src/components/Common/Modal/Modal.jsx
  src/components/Survey/Common/SurveySection.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step2.jsx
  src/components/Survey/UserSteps/Step3.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/components/Survey/UserSteps/Step5.jsx
  src/components/Survey/UserSteps/Step6.jsx
  src/components/Survey/UserSteps/Step7.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/store/useSurveyGroomerStore.js
  src/store/useSurveyUserStore.js
Labels: 🔨 Refactor, ✨ Feature

#77 회원가입 반려견, 미용사 프로필 등록
  src/api/profile.js
  src/api/requestUrls.js
  src/components/Common/Selector/Selector.jsx
  src/components/Features/ProfileSelector.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/components/Survey/GroomerSteps/Step6.jsx
  src/components/Survey/GroomerSteps/Step7.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step2.jsx
  src/components/Survey/UserSteps/Step3.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/components/Survey/UserSteps/Step5.jsx
  src/components/Survey/UserSteps/Step6.jsx
  src/components/Survey/UserSteps/Step7.jsx
  src/constants/features.js
  src/constants/services.js
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/store/useSurveyGroomerStore.js
  src/store/useSurveyUserStore.js
Labels: 📬 API, ✨ Feature

#84 set role as global state
  src/api/auth.js
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
Labels: ✨ Feature

#85 리뷰 작성, 수정, 삭제, 조회 API 연동
  src/api/requestUrls.js
  src/api/review.js
  src/components/Features/ImageSelector.jsx
  src/components/Features/ReviewAccordion.jsx
  src/components/Features/ReviewStars.jsx
  src/pages/NewReview.jsx
  src/pages/SalonProfile.jsx
  src/pages/mypage/EditReview.jsx
  src/pages/mypage/MyReviews.jsx
  src/pages/mypage/MySalonPage.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 📬 API, ✨ Feature

#90 콘테스트 API 매핑 📬 API ✨ Feature
  src/api/contestApi.js
  src/components/Contest/Feed.jsx
  src/pages/Contest/Contest.jsx
  src/pages/Contest/ContestEntry.jsx
Labels: 📬 API, ✨ Feature

#98 Netlify: redirecting to subdomain
  public/_redirects
Labels: 🌏 Deploy

#96 main api connection
  src/api/contest.js
  src/api/home.js
  src/api/requestUrls.js
  src/pages/Contest/Contest.jsx
  src/pages/Contest/ContestResult.jsx
  src/pages/ContestResult.jsx
  src/pages/Home.jsx
Labels: 📬 API

#100 유효성검사 유틸 추가
  public/_redirects
  src/api/dogProfile.js
  src/api/socialProfile.js
  src/components/Features/ImageSelector.jsx
  src/components/Features/ProfileSelector.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/components/Survey/GroomerSteps/Step7.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step2.jsx
  src/components/Survey/UserSteps/Step3.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/constants/breeds.js
  src/pages/NewReview.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditReview.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/utils/toastUtils.js
Labels: 🔨 Refactor, 🎨 Html&css, ✨ Feature

#107 알림 테스트 배포
  public/_redirects
  src/api/dogProfile.js
  src/api/socialProfile.js
  src/components/Features/ImageSelector.jsx
  src/components/Features/ProfileSelector.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/components/Survey/GroomerSteps/Step7.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step2.jsx
  src/components/Survey/UserSteps/Step3.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/constants/breeds.js
  src/pages/NewReview.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditReview.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/utils/toastUtils.js
Labels: 🌏 Deploy

#104 반응형 화면
  src/components/Common/Button/Button.jsx
  src/components/Common/Card.jsx
  src/components/Common/Modal/Modal.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/routes/AppRoutes.jsx
  src/themes.js
Labels: 🎨 Html&css

#103 결제내역페이지 api
  src/api/notification.js
  src/api/payment.js
  src/api/requestUrls.js
  src/pages/mypage/PaymentHistory.jsx
  src/utils/NotificationService.jsx
Labels: 📬 API

#111 버그 & 스타일링 수정
  src/api/dogProfile.js
  src/api/estimate.js
  src/api/groomerProfile.js
  src/api/notification.js
  src/api/review.js
  src/api/socialProfile.js
  src/components/Common/Button/Button.jsx
  src/components/Request/modules/SelectDog.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/firebase/firebase.js
  src/firebase/firebaseMessaging.js
  src/main.jsx
  src/pages/Notification.jsx
  src/pages/Survey/AddDogProfile.jsx
  src/pages/Survey/AddSalonProfile.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/utils/NotificationService.jsx
Labels: 🎨 Html&css, 🐞 BugFix

#113 알림 테스트 배포
  src/api/dogProfile.js
  src/api/estimate.js
  src/api/groomerProfile.js
  src/api/notification.js
  src/api/review.js
  src/api/socialProfile.js
  src/components/Common/Button/Button.jsx
  src/components/Request/modules/SelectDog.jsx
  src/components/Survey/GroomerSteps/Step5.jsx
  src/firebase/firebase.js
  src/firebase/firebaseMessaging.js
  src/main.jsx
  src/pages/Notification.jsx
  src/pages/Survey/AddDogProfile.jsx
  src/pages/Survey/AddSalonProfile.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/utils/NotificationService.jsx
Labels: 🌏 Deploy

#116 알림 테스트 배포
  public/firebase-messaging-sw.js
Labels: 🌏 Deploy

#119 알림 수정
  src/components/Common/Header/Header.jsx
  src/firebase/firebaseMessaging.js
  src/pages/Notification.jsx
Labels: ✨ Feature, 🐞 BugFix

#121 알림 테스트: commented out onmessage code
  src/components/Common/Header/Header.jsx
  src/firebase/firebaseMessaging.js
  src/pages/Notification.jsx
  src/routes/PrivateRoute.jsx
Labels: 🌏 Deploy, 🐞 BugFix

#128 remove toast error for groomer survey upon register
  src/pages/Survey/SurveyGroomer.jsx
Labels: 🐞 BugFix

#129 dog & social profile bugfixes
  src/api/dogProfile.js
  src/api/socialProfile.js
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
Labels: 🐞 BugFix

#130 버그 수정 사항 배포
  src/api/dogProfile.js
  src/api/socialProfile.js
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
Labels: 🌏 Deploy

#133 견적 요청, 견석서 작성 버그 수정
  src/components/Estimate/modules/SetDesc.jsx
  src/components/Request/modules/SelectServiceType.jsx
  src/components/Request/templates/SecondStep.jsx
  src/store/useRequestStore.js
Labels: 🐞 BugFix

#134 fixed continuous post fcmtoken
  src/firebase/firebaseMessaging.js
  src/routes/PrivateRoute.jsx
Labels: 🐞 BugFix

#135 알림 - removed unsubscribing / delete token
  src/firebase/firebaseMessaging.js
  src/pages/Notification.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🐞 BugFix

#136 fixed foreground notification
  src/pages/Notification.jsx
  src/routes/AppRoutes.jsx
Labels: 🐞 BugFix

#138 알림 리스너 윗단에 위치 & 토큰 새로고침에 발급 (일단) 허용
  src/components/Common/Header/Header.jsx
  src/firebase/FCMListener.jsx
  src/pages/Notification.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
Labels: 🐞 BugFix

#139 멘토링 피드백
  src/api/dogProfile.js
  src/components/Common/Checkbox/Checkbox.css
  src/components/Common/Checkbox/Checkbox.jsx
  src/components/Common/InputText/InputText.css
  src/components/Common/InputText/InputText.jsx
  src/components/Common/Selector/Selector.jsx
  src/components/Features/ServiceRegionForm.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/utils/toastUtils.js
Labels: 🎨 Html&css, ✨ Feature

#141 테스트 배포
  src/api/dogProfile.js
  src/components/Common/Checkbox/Checkbox.css
  src/components/Common/Checkbox/Checkbox.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/InputText/InputText.css
  src/components/Common/InputText/InputText.jsx
  src/components/Common/Selector/Selector.jsx
  src/components/Estimate/modules/SetDesc.jsx
  src/components/Features/ServiceRegionForm.jsx
  src/components/Request/modules/SelectServiceType.jsx
  src/components/Request/templates/SecondStep.jsx
  src/components/Survey/GroomerSteps/Step1.jsx
  src/components/Survey/GroomerSteps/Step2.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/components/Survey/GroomerSteps/Step4.jsx
  src/components/Survey/UserSteps/Step1.jsx
  src/components/Survey/UserSteps/Step4.jsx
  src/firebase/FCMListener.jsx
  src/firebase/firebaseMessaging.js
  src/pages/Notification.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/store/useRequestStore.js
  src/utils/toastUtils.js
Labels: 🌏 Deploy

#142 견적서 삭제(미용사가) api에 groomerId 추가
  src/pages/mypage/RequestHistory.jsx
Labels: 🐞 BugFix

#147 견적요청 삭제(미용사가) 삭제하고 리스트 리프레시
  src/pages/mypage/RequestHistory.jsx
Labels: 🐞 BugFix

#150 Bugfixes
  src/components/Common/Checkbox/Checkbox.css
  src/components/Common/DateModal.jsx
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Features/BadgeDisplay.jsx
  src/components/Request/atoms/PetItem.jsx
  src/components/Request/atoms/SelectDogItem.jsx
  src/components/Request/atoms/SubTitle.jsx
  src/components/Request/modules/PetList.jsx
  src/components/Request/modules/SelectDate.jsx
  src/components/Request/modules/SelectDog.jsx
  src/components/Request/modules/SelectDogImg.jsx
  src/components/Request/modules/SelectService.jsx
  src/components/Request/modules/SelectServiceType.jsx
  src/components/Request/modules/SelectSignificant.jsx
  src/components/Request/templates/DogFirstStep.jsx
  src/components/Request/templates/DogSecondStep.jsx
  src/components/Request/templates/FirstStep.jsx
  src/components/Request/templates/NewRequest.jsx
  src/components/Request/templates/SecondStep.jsx
  src/components/Request/templates/ThirdStep.jsx
  src/firebase/FCMListener.jsx
  src/firebase/firebaseMessaging.js
  src/pages/NewRequest.jsx
  src/pages/SalonProfile.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/Mypage.jsx
  src/pages/mypage/RequestHistory.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/PrivateRoute.jsx
  src/utils/toastUtils.js
Labels: 🎨 Html&css, 🐞 BugFix

#151 coupon api
  src/api/coupon.js
  src/api/requestUrls.js
  src/components/Common/Navbar/Navbar.jsx
  src/pages/Coupon.jsx
  src/pages/Home.jsx
  src/pages/coupon/Coupon.jsx
  src/pages/coupon/CouponImage.jsx
  src/pages/mypage/MyCoupons.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/routes/paths.jsx
  src/store/useUserStore.js
Labels: 📬 API

#153 우리아이 시뮬레이션 기능구현
  src/api/generateimage.js
  src/api/requestUrls.js
  src/components/Common/Button/Button.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/components/Request/modules/SelectDogImg.jsx
  src/components/Request/modules/SelectSignificant.jsx
  src/pages/Simulation.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 📬 API, 🎨 Html&css, ✨ Feature

#155 쿠폰, 우아시 배포
  src/api/coupon.js
  src/api/generateimage.js
  src/api/requestUrls.js
  src/components/Common/Button/Button.jsx
  src/components/Common/Checkbox/Checkbox.css
  src/components/Common/DateModal.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Features/BadgeDisplay.jsx
  src/components/Request/atoms/PetItem.jsx
  src/components/Request/atoms/SelectDogItem.jsx
  src/components/Request/atoms/SubTitle.jsx
  src/components/Request/modules/PetList.jsx
  src/components/Request/modules/SelectDate.jsx
  src/components/Request/modules/SelectDog.jsx
  src/components/Request/modules/SelectDogImg.jsx
  src/components/Request/modules/SelectService.jsx
  src/components/Request/modules/SelectServiceType.jsx
  src/components/Request/modules/SelectSignificant.jsx
  src/components/Request/templates/DogFirstStep.jsx
  src/components/Request/templates/DogSecondStep.jsx
  src/components/Request/templates/FirstStep.jsx
  src/components/Request/templates/NewRequest.jsx
  src/components/Request/templates/SecondStep.jsx
  src/components/Request/templates/ThirdStep.jsx
  src/firebase/FCMListener.jsx
  src/firebase/firebaseMessaging.js
  src/pages/Coupon.jsx
  src/pages/Home.jsx
  src/pages/NewRequest.jsx
  src/pages/SalonProfile.jsx
  src/pages/Simulation.jsx
  src/pages/coupon/Coupon.jsx
  src/pages/coupon/CouponImage.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/MyCoupons.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/Mypage.jsx
  src/pages/mypage/RequestHistory.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/routes/paths.jsx
  src/store/useUserStore.js
  src/utils/toastUtils.js
Labels: 🌏 Deploy

#110 콘테스트 페이지 일부 수정
  package-lock.json
  src/api/contest.js
  src/api/contestApi.js
  src/api/requestUrls.js
  src/components/Common/Card.jsx
  src/components/Common/Modal/Modal.jsx
  src/components/Contest/Feed.jsx
  src/components/Contest/WinnerProfile.jsx
  src/pages/Contest/Contest.jsx
  src/pages/Contest/ContestEntry.jsx
  src/pages/Contest/ContestResult.jsx
  src/pages/Home.jsx
  src/routes/PrivateRoute.jsx
  src/store/useLikeStore.js
  src/utils/toastUtils.js
Labels: 🎨 Html&css

#154 design & feature fixes
  src/components/Common/Header/Header.jsx
  src/components/Contest/WinnerProfile.jsx
  src/components/Features/ReviewAccordion.jsx
  src/components/Layout/Loading.jsx
  src/components/Request/templates/ThirdStep.jsx
  src/components/Survey/UserSteps/Step6.jsx
  src/pages/Contest/Contest.jsx
  src/pages/Contest/ContestResult.jsx
  src/pages/Home.jsx
  src/pages/NewRequest.jsx
  src/pages/SalonPublicProfile/SalonDetail.jsx
  src/pages/SalonPublicProfile/SalonProfile.jsx
  src/pages/SalonReviews.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/coupon/CouponImage.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/pages/mypage/MyReviews.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/PaymentHistory.jsx
  src/pages/mypage/RequestHistory.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/AppRoutes.jsx
  src/routes/PrivateRoute.jsx
  src/store/useSurveyUserStore.js
  src/themes.js
Labels: 🔨 Refactor, 🎨 Html&css, ✨ Feature, 🐞 BugFix

#163 QA 수정
  src/components/Chatting/atoms/MyRequestItem.jsx
  src/components/Chatting/modules/ChatHeader.jsx
  src/components/Chatting/modules/ChatRoomHeader.jsx
  src/components/Chatting/modules/ListItem.jsx
  src/components/Chatting/templates/Chatmain.jsx
  src/components/Estimate/modules/SetDesc.jsx
  src/components/Request/atoms/SelectDogItem.jsx
  src/pages/chat/Pay.jsx
  src/pages/chat/PaySuccess.jsx
  src/pages/mypage/PaymentHistory.jsx
  src/pages/mypage/RequestHistory.jsx
Labels: 🔨 Refactor, 🐞 BugFix

#168 쿠폰, 콘테스트, 구독알림 등 수정
  src/api/auth.js
  src/api/notification.js
  src/api/requestUrls.js
  src/components/Common/Modal/Modal.jsx
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Contest/Feed.jsx
  src/components/Features/ImageSelector.jsx
  src/components/Survey/GroomerSteps/Step3.jsx
  src/firebase/firebaseMessaging.js
  src/pages/Contest/Contest.jsx
  src/pages/Contest/ContestEntry.jsx
  src/pages/Contest/ContestPosts.jsx
  src/pages/Contest/ContestResult.jsx
  src/pages/Home.jsx
  src/pages/SalonPublicProfile/SalonDetail.jsx
  src/pages/SalonPublicProfile/SalonProfile.jsx
  src/pages/coupon/Coupon.jsx
  src/store/useUserStore.js
  src/utils/toastUtils.js
Labels: 🔨 Refactor, 📬 API, 🎨 Html&css, 🐞 BugFix

#172 Fixes
  package-lock.json
  package.json
  src/api/auth.js
  src/api/notification.js
  src/api/request.js
  src/components/Chatting/atoms/ChattingItem.jsx
  src/components/Chatting/modules/ChatRoomHeader.jsx
  src/components/Chatting/modules/ListItem.jsx
  src/components/Common/DateModal.jsx
  src/components/Common/RegionModal/KoreaRegions.js
  src/components/Estimate/atoms/ChargeInput.jsx
  src/components/Estimate/modules/SetDesc.jsx
  src/components/Estimate/templates/EditFristStep.jsx
  src/components/Estimate/templates/FirstStep.jsx
  src/components/Request/atoms/Selector2.jsx
  src/components/Request/modules/SelectDate.jsx
  src/pages/Contest/Contest.jsx
  src/pages/Notification.jsx
  src/pages/chat/Pay.jsx
  src/pages/estimate/ViewEstimate.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/Mypage.jsx
  src/pages/mypage/RequestHistory.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/PrivateRoute.jsx
Labels: 🔨 Refactor, 🎨 Html&css, ✨ Feature, 🐞 BugFix

#173 QA 작업3
  src/components/Chatting/modules/ChatNavbar.jsx
  src/components/Chatting/modules/ChatRoomHeader.jsx
  src/components/Chatting/templates/ChatRoomMain.jsx
  src/components/Chatting/templates/Chatmain.jsx
  src/pages/chat/ChatRoom.jsx
  src/pages/chat/MyRequest.jsx
  src/pages/chat/MyRequestDetail.jsx
  src/pages/chat/Pay.jsx
  src/pages/estimate/ViewEstimate.jsx
  src/pages/mypage/MyCoupons.jsx
  src/pages/mypage/PaymentHistory.jsx
  src/pages/mypage/RequestHistory.jsx
Labels: 🔨 Refactor, 🐞 BugFix
