Repository Ureca-Dangdang-salon/dang_client, pull requests merged in 2024-11, with the labels that each got.

#4 Design: storybook setting and building components
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  .storybook/preview.jsx
  package-lock.json
  package.json
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/themes.js
Labels: 🎨 Html&css

#12 Feat: Header & Navbar
  src/components/Common/DetailHeader.jsx
  src/components/Common/DetailHeader.stories.js
  src/components/Common/Header.jsx
  src/components/Common/Header.stories.js
  src/components/Common/Navbar.jsx
  src/components/Common/Navbar.stories.js
  src/components/Common/SurveyHeader.jsx
  src/components/Common/SurveyHeader.stories.js
  src/components/Common/header.css
  src/components/Common/navbar.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/NewRequest.jsx
  src/pages/Notification.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
  src/stories/Navbar.jsx
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/page.css
Labels: 🎨 Html&css, ✨ Feature

#13 Style: modal
  src/components/Common/SurveyHeader.jsx
  src/stories/MainModal.jsx
  src/stories/MainModal.stories.js
Labels: 🎨 Html&css

#14 Style/#3 storybook2
  src/stories/AddButton.css
  src/stories/AddButton.jsx
  src/stories/AddButton.stories.jsx
  src/stories/NumberPicker.css
  src/stories/NumberPicker.jsx
  src/stories/NumberPicker.stories.jsx
  src/stories/RadioButton.css
  src/stories/RadioButton.jsx
  src/stories/RadioButton.stories.jsx
Labels: 🎨 Html&css

#17 fix : 간단한 스타일 수정
  package-lock.json
  package.json
  src/components/Common/AddButton/AddButton.css
  src/components/Common/AddButton/AddButton.jsx
  src/components/Common/AddButton/AddButton.stories.jsx
  src/components/Common/Button/Button.css
  src/components/Common/Button/Button.jsx
  src/components/Common/Button/Button.stories.jsx
  src/components/Common/Configure.mdx
  src/components/Common/DetailHeader/DetailHeader.jsx
  src/components/Common/DetailHeader/DetailHeader.stories.jsx
  src/components/Common/Header/Header.css
  src/components/Common/Header/Header.jsx
  src/components/Common/Header/Header.stories.jsx
  src/components/Common/InputText/InputText.css
  src/components/Common/InputText/InputText.jsx
  src/components/Common/InputText/InputText.stories.jsx
  src/components/Common/Modal/Modal.jsx
  src/components/Common/Modal/Modal.stories.jsx
  src/components/Common/Navbar/Navbar.css
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/Navbar/Navbar.stories.jsx
  src/components/Common/NumberPicker/NumberPicker.css
  src/components/Common/NumberPicker/NumberPicker.jsx
  src/components/Common/NumberPicker/NumberPicker.stories.jsx
  src/components/Common/RadioButton/RadioButton.css
  src/components/Common/RadioButton/RadioButton.jsx
  src/components/Common/RadioButton/RadioButton.stories.jsx
  src/components/Common/Selector/Selector.jsx
  src/components/Common/Selector/Selector.stories.jsx
  src/components/Common/SurveyHeader/SurveyHeader.jsx
  src/components/Common/SurveyHeader/SurveyHeader.stories.jsx
  src/components/Common/assets/accessibility.png
  src/components/Common/assets/accessibility.svg
  src/components/Common/assets/addon-library.png
  src/components/Common/assets/assets.png
  src/components/Common/assets/avif-test-image.avif
  src/components/Common/assets/context.png
  src/components/Common/assets/discord.svg
  src/components/Common/assets/docs.png
  src/components/Common/assets/figma-plugin.png
  src/components/Common/assets/github.svg
  src/components/Common/assets/share.png
  src/components/Common/assets/styling.png
  src/components/Common/assets/testing.png
  src/components/Common/assets/theming.png
  src/components/Common/assets/tutorials.svg
  src/components/Common/assets/youtube.svg
  src/pages/Home.jsx
  src/routes/AppRoutes.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/stories/button.css
Labels: 🎨 Html&css

#20 Fix layout
  public/images/default-dog-profile.png
  public/images/default-groomer-profile.png
  public/images/upload-profile-button.png
  src/components/Common/Header/Header.css
  src/components/Common/Header/Header.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/main.jsx
  src/pages/Mypage.jsx
  src/routes/AppRoutes.jsx
Labels: 🔨 Refactor

#21 fix: header back button
  src/components/Common/DetailHeader/DetailHeader.jsx
  src/components/Common/SurveyHeader/SurveyHeader.jsx
Labels: 🎨 Html&css, 🐞 BugFix

#22 Feat: 내 정보 페이지 마크업
  eslint.config.js
  public/images/upload-dog-button.png
  public/images/upload-picture.png
  src/components/Common/AddButton/AddButton.jsx
  src/components/Common/Button/Button.jsx
  src/components/Common/DetailHeader/DetailHeader.jsx
  src/components/Common/InputText/InputText.css
  src/components/Common/InputText/InputText.jsx
  src/components/Common/NumberPicker/NumberPicker.css
  src/components/Common/NumberPicker/NumberPicker.jsx
  src/components/Common/RadioButton/RadioButton.css
  src/components/Common/RadioButton/RadioButton.jsx
  src/components/Common/Selector/Selector.jsx
  src/components/Common/SurveyHeader/SurveyHeader.jsx
  src/pages/DogProfile.jsx
  src/pages/EditSocialProfile.jsx
  src/pages/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#23 Style: searchable selector & 내 정보 마크업 마무리
  public/icons/StarBorderRounded.png
  public/icons/StarHalfRounded.png
  public/icons/StarRounded.png
  src/components/Common/AddButton/AddButton.css
  src/components/Common/DetailHeader/DetailHeader.jsx
  src/components/Common/Header/Header.css
  src/components/Common/InputText/InputText.css
  src/components/Common/InputText/InputText.jsx
  src/components/Common/Modal/Modal.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/NumberPicker/NumberPicker.css
  src/components/Common/RadioButton/RadioButton.css
  src/components/Common/Selector/Selector.jsx
  src/constants/breeds.js
  src/pages/DogProfile.jsx
  src/pages/Mypage.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#25 Style: 결제 내역 페이지 마크업
  src/components/Common/DetailHeader/DetailHeader.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/PaymentHistory.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
  src/themes.js
Labels: 🎨 Html&css

#29 쿠폰함 마크업
  public/images/coupon.png
  src/pages/mypage/MyCoupons.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#32 Feat/#31 number picker input
  src/components/Common/NumberPicker/NumberPicker.css
  src/components/Common/NumberPicker/NumberPicker.jsx
  src/components/Common/NumberPicker/NumberPicker.stories.jsx
  src/components/Common/assets/googleicon.svg
  src/components/Common/assets/kakaoicon.svg
  src/components/Common/assets/logo.svg
  src/components/Common/assets/navericon.svg
  src/components/login/GLoginButton.jsx
  src/components/login/KLoginButton.jsx
  src/components/login/NLoginButton.jsx
  src/pages/Login.jsx
Labels: 🎨 Html&css

#33 견적 요청 마크업
  package-lock.json
  package.json
  src/components/Common/DateModal.jsx
  src/components/Common/RegionModal/KoreaRegions.js
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Common/SurveyHeader/SurveyHeader.jsx
  src/components/NewRequest/atoms/PetItem.jsx
  src/components/NewRequest/atoms/SelectDogItem.jsx
  src/components/NewRequest/atoms/Selector2.jsx
  src/components/NewRequest/atoms/SubTitle.jsx
  src/components/NewRequest/modules/PetList.jsx
  src/components/NewRequest/modules/SelectDate.jsx
  src/components/NewRequest/modules/SelectDog.jsx
  src/components/NewRequest/modules/SelectDogImg.jsx
  src/components/NewRequest/modules/SelectRegion.jsx
  src/components/NewRequest/modules/SelectService.jsx
  src/components/NewRequest/modules/SelectServiceType.jsx
  src/components/NewRequest/modules/SelectSignificant.jsx
  src/components/NewRequest/templates/DogFirstStep.jsx
  src/components/NewRequest/templates/DogSecondStep.jsx
  src/components/NewRequest/templates/FirstStep.jsx
  src/components/NewRequest/templates/NewRequest.jsx
  src/components/NewRequest/templates/SecondStep.jsx
  src/pages/NewRequest.jsx
  src/store/usePageStore.js
Labels: 🎨 Html&css

#35 리뷰 작성하기, 나의 리뷰, 나에게 남긴 리뷰 페이지 마크업
  src/components/Features/ReviewStars.jsx
  src/pages/NewReview.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/MyReviews.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/MyUserPage.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#37 견적서 작성 페이지 마크업
  src/components/Common/TextArea/TextArea.jsx
  src/components/NewEstimate/atoms/ChargeInput.jsx
  src/components/NewEstimate/modules/DogProfile.jsx
  src/components/NewEstimate/modules/SetCharge.jsx
  src/components/NewEstimate/modules/SetDesc.jsx
  src/components/NewEstimate/templates/DetailStep.jsx
  src/components/NewEstimate/templates/EditStep.jsx
  src/components/NewEstimate/templates/FirstStep.jsx
  src/components/NewRequest/atoms/SelectDogItem.jsx
  src/components/NewRequest/atoms/Selector2.jsx
  src/components/NewRequest/atoms/SubTitle.jsx
  src/components/NewRequest/modules/SelectDog.jsx
  src/components/NewRequest/modules/SelectSignificant.jsx
  src/components/NewRequest/templates/SecondStep.jsx
  src/pages/NewRequest.jsx
  src/pages/estimate/EditEstimate.jsx
  src/pages/estimate/NewEstimate.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
  src/store/usePageStore.js
Labels: 🎨 Html&css

#41 견적요청내역, 견적요청상세보기 마크업
  src/components/Common/AddButton/AddButton.css
  src/components/Common/Button/Button.css
  src/components/Common/Button/Button.jsx
  src/components/Common/Header/Header.css
  src/components/Common/Modal/Modal.jsx
  src/components/Features/DogCompareImg.jsx
  src/components/NewEstimate/modules/DogProfile.jsx
  src/pages/mypage/MyReviews.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/PaymentHistory.jsx
  src/pages/mypage/RequestHistory.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#42 홈페이지, 기타 순위 보기 페이지 마크업
  package-lock.json
  package.json
  public/icons/coupon.png
  public/images/winner.png
  src/components/Common/Card.jsx
  src/components/Common/TextArea/TextArea.jsx
  src/pages/ContestResult.jsx
  src/pages/Home.jsx
  src/pages/NewReview.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/RequestHistoryDetail.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#39 설문조사 페이지 마크업
  package-lock.json
  package.json
  public/images/upload-groomer-profile.png
  src/components/Common/Button/Button.css
  src/components/Common/Button/Button.jsx
  src/components/Common/DeleteButton/DeleteButton.jsx
  src/components/Common/DeleteButton/DeleteButton.stories.jsx
  src/pages/Login.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
  vite.config.js
Labels: 🎨 Html&css

#45 채팅 페이지 마크업
  public/images/EmptyIcon.png
  src/components/Chatting/atoms/ChattingItem.jsx
  src/components/Chatting/atoms/DetailItem.jsx
  src/components/Chatting/atoms/MyRequestItem.jsx
  src/components/Chatting/modules/ChatHeader.jsx
  src/components/Chatting/modules/ChatNavbar.jsx
  src/components/Chatting/modules/ChatRoomHeader.jsx
  src/components/Chatting/modules/ListItem.jsx
  src/components/Chatting/templates/ChatRoomMain.jsx
  src/components/Chatting/templates/Chatmain.jsx
  src/components/Chatting/templates/EmptyContent.jsx
  src/components/Common/Button/Button.jsx
  src/pages/Chat.jsx
  src/pages/chat/Chat.jsx
  src/pages/chat/ChatRoom.jsx
  src/pages/chat/MyRequest.jsx
  src/pages/chat/MyRequestDetail.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#48 리뷰 작성 페이지 구현
  package-lock.json
  package.json
  src/components/Common/Button/Button.css
  src/components/Common/Button/Button.jsx
  src/components/Features/ImageSelector.jsx
  src/pages/Home.jsx
  src/pages/NewReview.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/pages/mypage/EditSalonProfile.jsx
Labels: ✨ Feature

#59 fix/button and login page layout
  src/components/Common/Modal/Modal.jsx
  src/components/login/GLoginButton.jsx
  src/components/login/NLoginButton.jsx
  src/pages/Login.jsx
  src/pages/Survey/Survey.jsx
  src/pages/Survey/SurveyGroomer.jsx
  src/pages/Survey/SurveyUser.jsx
  src/routes/AppRoutes.jsx
Labels: 🎨 Html&css, 🐞 BugFix

#58 내정보 페이지 기능 구현
  src/components/Common/RadioButton/RadioButton.jsx
  src/components/Features/CertificationsForm.jsx
  src/components/Features/ProfileSelector.jsx
  src/components/Features/ReviewStars.jsx
  src/components/Features/ServiceRegionForm.jsx
  src/components/NewRequest/atoms/Selector2.jsx
  src/pages/mypage/DogProfile.jsx
  src/pages/mypage/EditSalonProfile.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/pages/mypage/MySalonPage.jsx
  src/pages/mypage/MyUserPage.jsx
  src/pages/mypage/Mypage.jsx
  src/routes/AppRoutes.jsx
Labels: ✨ Feature

#60 콘테스트 페이지 마크업
  public/images/contest-winner.png
  public/images/dog.png
  src/components/Contest/Feed.jsx
  src/pages/Contest.jsx
  src/pages/ContestEntry.jsx
  src/routes/AppRoutes.jsx
  src/routes/paths.jsx
Labels: 🎨 Html&css

#63 feat: location selector complete
  src/components/Common/RegionModal/KoreaRegions.js
  src/components/Common/RegionModal/RegionModal.jsx
  src/components/Features/ServiceRegionForm.jsx
  src/components/NewRequest/modules/SelectRegion.jsx
  src/components/NewRequest/templates/SecondStep.jsx
  src/pages/Survey/Survey.jsx
  src/pages/mypage/EditSocialProfile.jsx
  src/routes/AppRoutes.jsx
Labels: ✨ Feature

#65 feat: notfound page
  public/images/notfound.png
  src/components/Layout/NotFound.jsx
Labels: 🎨 Html&css, ✨ Feature
